// User Actions
const SET_USER = 'SET_USER';
const GET_USER = 'GET_USER';
const LOG_OUT = 'LOG_OUT';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const CLEAR_ERROR = 'CLEAR_ERROR';

export {
  SET_USER,
  GET_USER,
  LOG_OUT,
  LOGIN_FAILURE,
  LOGIN_SUCCESS,
  CLEAR_ERROR,
};

// UI Actions
const IS_LOADING = 'IS_LOADING';
const IS_NOT_LOADING = 'IS_NOT_LOADING';

export { IS_LOADING, IS_NOT_LOADING };
