const SET_USER = 'SET_USER';
const GET_USER = 'GET_USER';
const LOG_OUT = 'LOG_OUT';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export { SET_USER, GET_USER, LOG_OUT, LOGIN_FAILURE, LOGIN_SUCCESS };
