// User Actions
const SET_USER = 'SET_USER';
const GET_USER = 'GET_USER';
const LOG_OUT = 'LOG_OUT';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export {
  SET_USER,
  GET_USER,
  LOG_OUT,
  LOGIN_FAILURE,
  LOGIN_SUCCESS,
  CLEAR_MESSAGE,
  SIGN_UP_FAILURE,
  SIGN_UP_SUCCESS,
};

// UI Actions
const IS_LOADING = 'IS_LOADING';
const IS_NOT_LOADING = 'IS_NOT_LOADING';

export { IS_LOADING, IS_NOT_LOADING };
